import re

regex = r"cia?"

test_str = ("Informó que las conexiones entre la Inteligencia Artificial y otras ciencias van y vienen. Por un lado, la IA ha intentado replicar las capacidades y el comportamiento humanos, haciendo uso de estudios en Neurociencias, Lingüística y Cognición; por otro lado, estos a su vez se han beneficiado de los modelos computacionales creados con base en sus teorías, como en la Lingüística Computacional.\n"
	"El investigador del IPN manifestó que “nosotros estamos formados por las interacciones sociales, las cuales están fuertemente influenciadas por algoritmos de inteligencia artificial. Nosotros como ingenieros e investigadores tenemos la responsabilidad de moldear nuestra sociedad. No sólo debe importar el mejor puntaje en los métodos que creamos, sino también en su propósito, su impacto y su potencialidad”.")

matches = re.finditer(regex, test_str, re.MULTILINE)

for matchNum, match in enumerate(matches, start=1):
    
    print ("Match {matchNum} was found at {start}-{end}: {match}".format(matchNum = matchNum, start = match.start(), end = match.end(), match = match.group()))
    
    for groupNum in range(0, len(match.groups())):
        groupNum = groupNum + 1
        
        print ("Group {groupNum} found at {start}-{end}: {group}".format(groupNum = groupNum, start = match.start(groupNum), end = match.end(groupNum), group = match.group(groupNum)))
